# -*- coding: utf-8 -*-
"""DivisionPieChart.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x3sZGpI_aMi0496vsELnJlGtw8_hDMA5
"""

import pandas as pd
import plotly.express as px

df=pd.read_csv('DistrictKTime.csv')
df.head()

fig = px.pie(df, values='TOTAL', names='DIVISION', title='BD Divisionwise covid19')
fig.update_traces(textposition='inside', textinfo='percent')
fig.show()

fig = px.pie(df, values='TOTAL', names='DISTRICT', title='BD Divisionwise covid19')
fig.update_traces(textposition='inside', textinfo='percent')
fig.show()