# -*- coding: utf-8 -*-
"""polypractise.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-u6u44HpkCF5WATt_JdUobeTgD-0jUKk
"""

import numpy as np
from sklearn.metrics import r2_score
import matplotlib.pyplot as plt
from scipy import stats
import pandas as pd
import warnings
from numpy import diff

df=pd.read_csv('Narayanganj.csv')
df.head()

x1=df['Index']
x=df['again']
#fx=[]
#for i in range(len(x)):
  #fx.append(x[i])

plt.plot(x1,x)
plt.show()

#z = np.polyfit(x1, x, 4)   ## fitting of the order of 4 

z, res, _, _, _ = np.polyfit(x1, x,5, full=True)   ## fitting of the order of 4

p = np.poly1d(z)#************
p

xp = np.linspace(1, 18, 18)  ## create 11 linearly spaced points between the minimum and maximum range of index 
plt.plot(x1, x, '*', xp, p(xp) )#**********************
plt.title("5th order polynomial")
plt.savefig("NarayanPoly")

dx = 1   ##  the difference between points of xp array now its 1
dy=diff(p(xp))/dx;#**************8
dy

plt.plot(dy)  ## actually plot versus xp(2 to end) ; no of differential will be 1 less than the total points in xp
plt.title("1st order differentiation")
plt.savefig('NarayanDiff')

s=np.sum(np.power((p(xp)-x),2))   ## s is the indication of the fitness 

print(s)#***********