# -*- coding: utf-8 -*-
"""BdDistrict.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mgkXwp6QwS9MpRpx9IsQvkoPqIyzqtJU
"""

!pip install pycountry

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
#recovered = recovered.fillna('unknow')
#deaths = deaths.fillna('unknow')


# Visualisation libraries
import matplotlib.pyplot as plt
# %matplotlib inline

sns.set()
from plotly.offline import init_notebook_mode, iplot 
import plotly.graph_objs as go
import plotly.offline as py
import pycountry
py.init_notebook_mode(connected=True)
import folium 
from folium import plugins

data=pd.read_csv('DistrictMap.csv',)
data.head()

District_map = folium.Map(location=[23.8103, 90.4125], zoom_start=7,tiles='Stamen Terrain')#"Stamen Terrain", "Stamen Toner", "Mapbox Bright"

for lat, lon, value, name in zip(data['lat'], data['lon'], data['Confirmed'], data['District']):
    folium.CircleMarker([lat, lon],
                        radius=.04*value,
                        popup = ('<strong>District</strong>: ' + str(name).capitalize() + '<br>'
                                '<strong>Confirmed Cases</strong>: ' + str(value) + '<br>'),
                        color='red',
                        
                        fill_color='red',
                        fill_opacity=0.5 ).add_to(District_map)
#print map
District_map