# -*- coding: utf-8 -*-
"""DIstrictClhloropeth.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qIR_CS0nDqtsMHeKf_czgEtDcfg5oYmZ
"""

import numpy as np
import pandas as pd
import seaborn as sns
import folium
import webbrowser
from folium.plugins import HeatMap

posi=pd.read_csv('DistrictMap.csv') # Get seismic data stored on your computer
#print (posi)
num = 7  ## assuming to start from 0 so total num+1  data points here 

lat = np.array(posi['lat'][0:num+1]) # Get latitude value
lon = np.array(posi['lon'][0:num+1]) # Get longitude value
js = np.array(posi['Confirmed'][0:num+1],dtype=float) # Convert to numpy floating point data

#print(js)

data1 = [[lat[i],lon[i],js[i]] for i in range(num+1)] # Specification data format
map_osm = folium.Map(location=[23.8103,90.412],zoom_start=7,tiles='Stamen Terrain',control_scale=True)
HeatMap(data1).add_to(map_osm) # Add heat map to the previously created map
#print(data1)
#map_osm
file_path='E:\Corona\test2.html'
print(data1)
map_osm.save(file_path) # Save as html file
webbrowser.open(file_path) # Default browser open

map_osm