# -*- coding: utf-8 -*-
"""TImeChloro.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l15K5BPW5P4Kbv6Nb1otLd2iYBu7f1xO
"""

import numpy as np
import pandas as pd
import seaborn as sns
import folium
import webbrowser
import  xlrd
from folium.plugins import HeatMap # Call various libraries

prefix=''
date=10
month='May'
extension='.csv'
num = 178 ## assuming to start from 0 so total num+1  data points here 
filename= ('map_doc-')+prefix+str(date)+'-'+month+'-'+'2020.csv'
print(filename)

posi=pd.read_csv(filename)
print(posi)

lat = np.array(posi['Var1'][0:num+1],dtype=float) # Get latitude value
lon = np.array(posi['Var2'][0:num+1],dtype=float) # Get latitude value


js = np.array(posi['Var3'][0:num+1],dtype=float) # Convert to numpy floating point data
#print(js)

data1 = [[lat[i],lon[i], js[i]] for i in range(num+1)] # Specification data format

map_osm = folium.Map(location=[23.728600, 90.385400 ],zoom_start=12,tiles='Stamen Terrain',control_scale=True)
HeatMap(data1,name='dihan',radius=15,max_val=.5).add_to(map_osm) # Add heat map to the previously created map
#file_path= ('map_')+str(date)+'-'+month+'-'+'2020.html'
#print(data1)
map_osm

#map_osm.save(file_path) # Save as html file
#webbrowser.open(file_path) # Default browser open