# -*- coding: utf-8 -*-
"""Corona.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/199Sz9J3Yec3AzCSOe9mtx0LfI3832S9Y
"""

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt # static data visulization 
import matplotlib.dates as mdates # datetime format 
import seaborn as sns # data visualization 
from datetime import datetime, timedelta
from plotly.offline import iplot,init_notebook_mode
import plotly.express as px 
import plotly.graph_objs as go

def configure_plotly_browser_state():
  import IPython
  display(IPython.core.display.HTML('''
        <script src="/static/components/requirejs/require.js"></script>
        <script>
          requirejs.config({
            paths: {
              base: '/static/base',
              plotly: 'https://cdn.plot.ly/plotly-latest.min.js?noext',
            },
          });
        </script>
        '''))

cnf = '#4B8BBE' # cyan blue
dth = '#ff2e63' # death - red
rec = '#21bf73' # recovered - cyan
act = '#9e3d64' # active case -purple

df= pd.read_csv('COVID19.csv')
df.head()

configure_plotly_browser_state()
# Create a new column for active case 
df['Active'] = df['Confirmed'] - df['Deaths'] - df['Recovered']
df.head()

configure_plotly_browser_state()
init_notebook_mode(connected=False)
# Grouping cases by date 
temp = df.groupby('Date')['Confirmed', 'Recovered', 'Deaths', 'Active'].sum().reset_index() 
# Unpivoting 
temp = temp.melt(id_vars='Date',value_vars = ['Confirmed', 'Recovered', 'Deaths', 'Active'], var_name='Case', value_name='Count') 

# Visualization
fig = px.line(temp, x='Date', y='Count', color='Case', color_discrete_sequence=[cnf, rec, dth, act], template='ggplot2') 
fig.update_layout(title="Number of COVID-19 Cases Overtime In Bangadesh")
#plt.savefig('line.png')
fig.show()



